services:
  gocd-server:
    image: gocd/gocd-server:v25.4.0
    container_name: gocd-server
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - gocd-server-data:/godata

  gocd-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: gocd-agent
    depends_on:
      - gocd-server
    environment:
      GO_SERVER_URL: http://gocd-server:8153/go
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  gocd-server-data: