FROM gocd/gocd-agent-ubuntu-22.04:v25.4.0

USER root

RUN apt update && \
    apt install -y curl docker.io && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt install -y nodejs && \
    groupadd docker || true && \
    usermod -aG docker go

USER go