format_version: 10

pipelines:
  react-app-pipeline:
    group: gocd_trial
    label_template: "${COUNT}"

    materials:
      git_repo:
        git: https://github.com/meetbikhani/gocd_trial.git
        branch: main

    stages:
      - lint:
          jobs:
            lint-job:
              tasks:
                - exec:
                    command: npm
                    arguments: ["install"]

                - exec:
                    command: npm
                    arguments: ["run", "lint"]

      - build:
          jobs:
            build-job:
              tasks:
                - exec:
                    command: npm
                    arguments: ["install"]

                - exec:
                    command: npm
                    arguments: ["run", "build"]

                - exec:
                    command: sh
                    arguments:
                      - -c
                      - docker build -t meetbikhani/jenkins_trial:v${GO_PIPELINE_COUNTER} .

      - deploy:
          jobs:
            deploy-job:
              tasks:
                - exec:
              command: sh
              arguments:
                - -c
                - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

                - exec:
                    command: sh
                    arguments:
                      - -c
                      - docker push meetbikhani/jenkins_trial:v${GO_PIPELINE_COUNTER}
